[package]
name = "runtimes"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/runtimes.rs"
doctest = false

[dependencies]
anyhow.workspace = true
# Note: terminal crate doesn't add alacritty to the workspace, so we directly depend on it here
alacritty_terminal = "0.23"
base64.workspace = true
collections.workspace = true
editor.workspace = true
gpui.workspace = true
futures.workspace = true
# Note: gpui crate doesn't pull image from the workspace
image = "0.23"
language.workspace = true
log.workspace = true
project.workspace = true
resvg = { version = "0.41.0", default-features = false }
runtimelib = "0.11.0"
serde.workspace = true
serde_json.workspace = true
settings.workspace = true
smol.workspace = true
tokio.workspace = true
theme.workspace = true
terminal_view.workspace = true
ui.workspace = true
util.workspace = true
uuid.workspace = true
usvg = { version = "0.41.0", default-features = false }
workspace.workspace = true

[dev-dependencies]
editor = { workspace = true, features = ["test-support"] }
env_logger.workspace = true
gpui = { workspace = true, features = ["test-support"] }
language = { workspace = true, features = ["test-support"] }
project = { workspace = true, features = ["test-support"] }
settings = { workspace = true, features = ["test-support"] }
theme = { workspace = true, features = ["test-support"] }
util = { workspace = true, features = ["test-support"] }
http = { workspace = true, features = ["test-support"] }
